### ISSUE TITLE
Error in "cv_landsat_collection_2" function

### ISSUE THREAD

**Issue by magipamies** [hectornieto/dms-bias-correction#1]
In the function "cv_landsat_collection_2" from the script "landsat_collection_2_helper.py", there may be an error when it temporarily saves the LST file because you need to resample the image before saving it.

This can be fixed by modifying the following lines:

```
# Save temporary LST file in K
temp_file = input_image / f"{input_image.stem}_ST.TIF"
sl.gu.saveImg(lst, gt, proj, str(temp_file), noDataValue=np.nan)
```
to:
```
# Save temporary LST file in K (prova)
proj1, gt1, xsize1, ysize1, extent1, _1 = sl.gu.getRasterInfo(str(raster))
temp_file1 = input_image / f"{input_image.stem}_ST1.TIF"
sl.gu.saveImg(lst, gt1, proj1, str(temp_file1), noDataValue=np.nan)
temp_file = input_image / f"{input_image.stem}_ST.TIF"
sl.gu.resampleWithGdalWarp(temp_file1, image_template, outFile=str(temp_file), outFormat="GTiff",  resampleAlg="near")
temp_file1.unlink()
```

**Comment by hectornieto** [comment]
The Coefficient of Variation is computed at coarser scale (based on `window_size` parameters), for both the reference and the sharpened LST (see lines [105](https://github.com/hectornieto/dms-bias-correction/blob/92e59a5bea948f4690a59e670e1eb902d134717a/dms_bias_correction/landsat_collection_2_helper.py#L105) and [107](https://github.com/hectornieto/dms-bias-correction/blob/92e59a5bea948f4690a59e670e1eb902d134717a/dms_bias_correction/landsat_collection_2_helper.py#L107)). 

These two values are then used to compute the scaling factor at the window_size domain (1000m by default). This scale factor, together with the local mean LST, are the ones that are resampled to the original resolution: [Lines 115-120](https://github.com/hectornieto/dms-bias-correction/blob/92e59a5bea948f4690a59e670e1eb902d134717a/dms_bias_correction/landsat_collection_2_helper.py#L115C1-L120C57)

**Comment by magipamies** [comment]
But I think it is saving the array of the original landsat image (30mx30) (line [164](https://github.com/hectornieto/dms-bias-correction/blob/92e59a5bea948f4690a59e670e1eb902d134717a/dms_bias_correction/landsat_collection_2_helper.py#L164)) with the georeferenced image obtained from the S3 sharpening (20m) (line [152](https://github.com/hectornieto/dms-bias-correction/blob/92e59a5bea948f4690a59e670e1eb902d134717a/dms_bias_correction/landsat_collection_2_helper.py#L152)).

**Comment by hectornieto** [comment]
I thihk I now understand your comment... you are right. The array mus be saved with the original geotransform. 

Then note that the actual resampling to the S3 sharpened image is then done within the  [local_variability](https://github.com/hectornieto/dms-bias-correction/blob/92e59a5bea948f4690a59e670e1eb902d134717a/dms_bias_correction/landsat_collection_2_helper.py#L165) call ([at line 184](https://github.com/hectornieto/dms-bias-correction/blob/92e59a5bea948f4690a59e670e1eb902d134717a/dms_bias_correction/scale_lst.py#L184))

Check for [new commit](https://github.com/hectornieto/dms-bias-correction/commit/08431c0554b293bdfb16cac961eb663923444999) and we could close the issue.

Thanks!
